### ISSUE TITLE
Map freezing/stuck random, coords Infinity

### ISSUE THREAD

**Issue by anibalardid** [img-mapper/react-img-mapper#54] opened 2022-10-17 20:12 UTC
**Describe the bug**
It doesnt happend on Firefox.
The problem is when you move the mouse cursor over the image map, sometimes it stills freeze, stuck.
Checking the code, it makes a math division, 
`            return coords.map(function (coord) { return coord / (imgRef.naturalWidth / parentWidth); });	`
and debugging it, sometimes 'imgRef.naturalWidth ' is zero (0) 

**Error Stack**
npm package version v1.3.0

You could see "infinity" coords on each element of map:
`<area shape="poly" coords="Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity" href="#" alt="map">`

**Expected behavior**
Don't do that :) 

**Screenshots**
![image](https://user-images.githubusercontent.com/1769919/196273710-d107e233-2de1-49e7-8fe8-74bc1a94158b.png)

**Desktop (please complete the following information):**
 - OS: Linux, Windows, MacOs
 - Browser: latest safari/chrome
 - Version: Chrome 105

**Comment by anibalardid** [comment] 2022-10-17 20:12
We have a fix

File:
dist/ImageMapper.js

Change:
`        if (responsive && parentWidth) {	`

by

`        if (responsive && parentWidth && imgRef.naturalWidth) {`

**Comment by NishargShah** [comment] 2022-10-19 16:24
Yes, it is not listed but you can directly download it from `npm`.

**Comment by ventsislavnikolov** [comment] 2022-11-07 10:12
Hi guys, can the fix be uploaded or PR merged? I have the same problem, sometimes/random the map doesn't work and show cords as infinity.

Thanks!

**Comment by DanielePancottini** [comment] 2022-11-24 18:26
Same problem :(

**Comment by NishargShah** [comment] 2022-11-24 20:20
Guys, I apologize for the lack of updates lately, but I will make sure to get them fixed by this weekend.

**Comment by DanielePancottini** [comment] 2023-02-06 09:05
anyone fixed this problem?

**Comment by ventsislavnikolov** [comment] 2023-02-06 15:33
I fixed this issues and some more on this fork - https://www.npmjs.com/package/reactjs-img-mapper / https://github.com/ventsislavnikolov/reactjs-img-mapper

**Comment by NishargShah** [comment] 2023-02-13 18:02
Duplicate of https://github.com/img-mapper/react-img-mapper/issues/42

**Closed by NishargShah** 2023-02-13 18:02 UTC
Labels: bug, duplicate, question
